services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: blog-app-backend

    restart: always

    ports:
      - '3000:3000'

    env_file:
      - .env

    depends_on:
      - redis

    volumes:
      - .:/app
      - /app/node_modules

    command: npm run start:dev

  redis:
    image: redis:8-alpine

    container_name: blog-app-redis

    restart: always

    volumes:
      - redis_data:/data

volumes:
  redis_data: